CREATE TABLE tb_alunos (
id BINARY(16) NOT NULL,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
senha VARCHAR(65) NOT NULL,
endereco VARCHAR(255),
cep DECIMAL(10),
PRIMARY KEY(id)
);

CREATE TABLE tb_funcionario (
id BINARY(16) NOT NULL,
nome VARCHAR(255) NOT NULL,
cargo VARCHAR(255) NOT NULL,
salario DECIMAL(6) NOT NULL,
departamento VARCHAR(255) NOT NULL,
idade DECIMAL(3) NOT NULL,
cpf VARCHAR(13) NOT NULL UNIQUE,
PRIMARY KEY(id)
);

CREATE TABLE tb_curso (
id BINARY(16) NOT NULL,
nome VARCHAR(255) NOT NULL,
disciplina VARCHAR(255) NOT NULL,
tempo_duracao DECIMAL(65) NOT NULL,
professor VARCHAR(65) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE tb_curso_aluno (
id_aluno BINARY(16) NOT NULL,
id_curso BINARY(16) NOT NULL,
FOREIGN KEY (id_aluno) REFERENCES tb_alunos(id),
FOREIGN KEY (id_curso) REFERENCES tb_curso(id)
);

CREATE DATABASE senai

USE senai

DROP TABLE tb_alunos